### ISSUE TITLE
[기타] Mui 벗어나기

### ISSUE THREAD

**Issue by chb09876** [Team-MTG/FrontEnd#10]

**Comment by chb09876** [comment]
Mui를 제거하고 사용할 css 라이브러리는 tailwind, styled-component, emotion 등이 있을거 같네요.

사용할 css 라이브러리에 대해 의견 주시면 감사하겠습니다.

**Comment by hyeonzii** [comment]
전 tailwind가 괜찮을거 같은데 저도 사용해보진 않아서 잘 모르겠네요....

**Comment by chb09876** [comment]
저도 tailwind 써보고 싶네요.

반응형 디자인도 지원하고 요즘 많이들 쓰는 추세 같아서 한번 써보고 어땟는지 알려드릴게영

**Comment by chb09876** [comment]
css 라이브러리리는 tailwind쓰는걸로 할게요!
