### ISSUE TITLE
[기능 추가] 그래프 컴포넌트 추가

### ISSUE THREAD

**Issue by chb09876** [Team-MTG/FrontEnd#11]
사용자가 주식을 구매/판매 한 시점을 보여주는 일봉 차트(또는 선 차트)를 보여줘야 합니다.

가로 스크롤이 가능한 그래프를 추가하여 적절한 범위의 정보를 보여줘야 할 것 같습니다.

**Comment by hyeonzii** [comment]
확인했습니다

**Comment by chb09876** [comment]
그래프는 직접 구현은 힘들 것 같고 라이브러리를 사용해야 하는데 제가 예전에 사용해봤던 chartJS는 개인적으로 좀 별로였던거 같아요.

공식문서가 친절한 편도 아니고 레퍼런스가 많이 없었습니다.

그래프 라이브러리에 대해서도 조사하고 결정할 필요가 있을거 같습니다!

**Comment by hyeonzii** [comment]
넵! 그래프 라이브러리 한 번 찾아보겠습니다

**Comment by mouse0429** [comment]
저도 기존엔 chartJS 썼었는데 귀여운 UI에 속았다는 느낌을 좀 받았습니다...ㅋㅋㅋ 커스텀 힘들었어요
간략하게 서치해보니 요즘 Nivo.roks 이걸 제일 선호하는 분위긴 것 같은데 이번 프로젝트에서 도입해보면 어떨까요?
공식 문서에도 응용 예제(바 그래프 들어갔을 때 차트레이스 구현 법을 알려주는 등) 를 다뤄주고 있는거보면 꽤나 친절한 편인 것 같아요

**Comment by chb09876** [comment]
nivo가 d3를 리액트에 맞춰서 감싼 라이브러리인가보네요! 원래 D3생각중이었는데 괜찮은거같아요!

**Comment by mouse0429** [comment]
저희 봉차트와 라인차트를 동시에보여줄일이 있나요? 두가지 차트를 겹쳐셔 보여주는게 안된다고 하는데..

**Comment by chb09876** [comment]
한 턴이 끝나고 종목이 공개되는 페이지에서 주가와 함께 매수/매도 시점을 표시하는 그래프를 보여줄려 했는데...
라인차트 두개는 겹칠수있나요?

**Comment by mouse0429** [comment]
라인차트 두개를 겹친다는게 아래 사진같은 경우를 말씀하시는건가요? 아래 사진은 공식홈페이지 라인차트 예제입니다!
<img width=600 src="https://user-images.githubusercontent.com/68915238/211466001-ccc811f6-3d10-4146-9af4-65be489e6da7.png"/>

**Comment by chb09876** [comment]
네 하나는 주가용 라인차트, 하나는 매수-매도 시점을 연결하는 라인차트로 디자인이 다른 차트가 겹쳐지는걸 생각하고 있어서용.
사실 매수-매도 시점은 라인차트가 아니더라도 차트상의 어떤 두 지점을 직선으로 이어주는 기능만 있어도 되긴해요!

**Comment by mouse0429** [comment]
일단 확인해본 바로는 다음과 같은 부분들이 가능합니다

1. 라인 커스텀 디자인
  <img width=600 src="https://user-images.githubusercontent.com/68915238/211478548-accb5f20-fb37-409f-9b97-8c3b5c588142.png"/>

2. 비선형 라인 그리기
이 정도의 자율성을 보장하는거보면 하나는 주가 표시 라인차트, 하나는 매수 매도 시점 연결 라인차트 조합이 가능할 것 같아요
<img width=600 src="https://user-images.githubusercontent.com/68915238/211479052-e1e16cd1-0ca3-4f9f-a1d2-95e8691b456d.png"/>

3. 마커 표시 가능
아니면 굳이 뭐 라인차트 두개를 쓰기보다는 이렇게 마커로 매수 매도 시점을 표시해줄 수도 있을 것 같아요
개인적으로는 이 마커가 좀 직관적으로 잘써볼 수 있을 것 같다는 생각이 듭니다!
<img width=100 src="https://user-images.githubusercontent.com/68915238/211478808-f500e02a-dc85-42fa-9822-4a9ca14f5631.png"/>

**Comment by chb09876** [comment]
Nivo(D3)결정
