### ISSUE TITLE
[기타] 도메인(주식) 관련 변수명 컨벤션 정하기

### ISSUE THREAD

**Issue by chb09876** [Team-MTG/FrontEnd#12]
주식 관련 변수명들이 동의어들이 혼재되어 있어 코드를 읽고 작성하는데 혼란이 있는거 같습니다.
예시) 수익률에 대해서 profit gain rate 등

그래서 이런 애매한 용어들에 대해서 어떤 이름을 사용할지 확실히 정하고 가면 좋을거 같아요!

제 개인적인 생각으론 백엔드 데이터 베이스에 있는 용어들을 따오는게 하나의 방법일거 같기도 합니다.

다른분들도 의견 주세요!

**Comment by chb09876** [comment]
지금 생각나는 정해야 되는 애들은 시드머니, 총 자산(주식 + 현금), 평단가, 보유 현금, 수익률 이 있네요

**Comment by hyeonzii** [comment]
넵 저 일단 수익률 profit 으로 하긴 했는데 확실하게 정하고 가는게 좋을 것 같습니다~~

**Comment by mouse0429** [comment]
백엔드와 일치시키는게 개인적으로는 가장 편했던 것 같습니다!
내일 회의에서 아예 정하고 가면 어떨까요?

**Comment by chb09876** [comment]
네 오늘 회의에서 정하는걸로 합시다!
