### ISSUE TITLE
[기능추가] MUI컴포넌트 Tailwind CSS로 교체

### ISSUE THREAD

**Issue by chb09876** [Team-MTG/FrontEnd#14]
현재 MUI컴포넌트들을 Tailwind 컴포넌트로 교체해야 합니다.

다만 1월 2일 디자인 회의 후 디자인 방향성이 잡히고 나서 하는게 좋을거 같아요.

**Comment by hyeonzii** [comment]
확인했습니다~

**Comment by chb09876** [comment]
https://jejupower.site/

주완님 디자인 나오기 전 까지는 이 사이트를 레퍼런스로 진행하겠습니다. 일단 저는 메인 페이지 작업 하고있을게요.

**Comment by hyeonzii** [comment]
넵~~

**Comment by chb09876** [comment]
메인페이지는 작업해서 Develop브랜치에 올려놨습니다!
게임 페이지 쪽 작업 들어갈게여

**Comment by hyeonzii** [comment]
방금 풀 땡겼는데 atoms에 others 라는 파일을 열 수 없다고 오류가 납니다..!! 제가 뭐 따로 추가할 거 있나요??

**Comment by chb09876** [comment]
> 방금 풀 땡겼는데 atoms에 others 라는 파일을 열 수 없다고 오류가 납니다..!! 제가 뭐 따로 추가할 거 있나요??

제 실수로 파일 이름 변경하고 불러오기 경로를 안바꿔주서 그런가봐요.
새로 올린 devlop브랜치 pull해주세요!

**Comment by chb09876** [comment]
게임 페이지도 작업 완료했습니다!

**Comment by hyeonzii** [comment]
넵~

**Comment by chb09876** [comment]
어느정도 MUI는 처리 된거 같아서 요기 이슈는 닫을게요!
