### ISSUE TITLE
[기타] 깃 전략 수립하기? 컨벤션 정하기?

### ISSUE THREAD

**Issue by chb09876** [Team-MTG/FrontEnd#9]
현재 무작정 develop브랜치에서 같이 작업중인데

git flow와 같은 전략들을 정하고 작업을 하면 어떨까요.

물론 전략들을 적용하면 그만큼 개발 속도는 늦춰질수도 있기에 고민과 논의가 필요할 것 같습니다.

또한 commit message convention도 정해보면 좋을거 같아요

**Comment by hyeonzii** [comment]
넵 알겠습니다!

**Comment by mouse0429** [comment]
프로젝트 기간이 짧으니 엄청 거창하게 깃 전략을 가져가기 보다는 심플하게 몇가지 정해두면 좋을 것 같습니다
현재 진행중인 다른 프로젝트에선 아래와 같은 규칙을 사용하고 있습니다

[브랜치]
<img width = 600, src="https://user-images.githubusercontent.com/68915238/211286404-74b60566-5ea8-4c6a-8a1c-51fbc91c35ff.png"/>

[커밋 메세지]
커밋 메세지의 경우 기존에 feat: ~~ 이런느낌으로 진행하셨던데 그렇게 진행해도 될 것 같고 완전히 한글로 진행한다면 아래와 같은 느낌도 괜찮을 것 같습니다
만약 feat: ~~ 느낌으로 진행한다면 feat, fix 등의 태그 유형만 정리하면 좋을 것 같아요
<img width = 600, src="https://user-images.githubusercontent.com/68915238/211286352-2c108030-484f-4a27-a4d9-8ad2ff0d9bc9.png"/>

**Comment by chb09876** [comment]
요 방법 좋은거 같네요! 한글로 하면 더 쉽게 알아볼 수 있을거같아여

**Comment by mouse0429** [comment]
이모지는 뭔가 매번 넣기 귀찮아서(좀 단순하게 넣는 툴 같은걸 추가하면 모를까) 위와 같이 했더니 편하긴 하더라구요!
그럼 브랜치, 커밋 메세지는 저렇게 갈까요? 뭔가 추가할 태그같은게 있을까요?

**Comment by chb09876** [comment]
일단 저대로 가고 나중에 필요한 태그 생기면 그때 추가하는걸로!
